service: swapi-serverless

useDotenv: true

plugins:
  - serverless-dotenv-plugin

build:
  esbuild:
    bundle: true
    minify: false
    packages: external
    buildConcurrency: 3
    sourcemap:
      type: external
      setNodeOptions: true

package:
  individually: true
  include:
    - .env

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 1024
  timeout: 29
  stage: ${opt:stage}
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
